# Generated by Django 4.2.7 on 2024-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0016_organismo_de_socorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasifcaso',
            name='codigo',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasifinal',
            name='codigo',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasifinicial',
            name='codigo',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuente',
            name='codigo',
            field=models.CharField(default=1, max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
