# Generated by Django 4.2.7 on 2024-04-03 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aseg', '0047_alter_repnovedad_eps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repnovedad',
            options={'ordering': ['-fecha'], 'verbose_name': 'Reporte de novedad', 'verbose_name_plural': 'Reportes de novedades'},
        ),
        migrations.RemoveField(
            model_name='formularioafil',
            name='tipoafiliado',
        ),
        migrations.CreateModel(
            name='Tipoafiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=1, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Tipo Afiliación',
                'verbose_name_plural': 'Tipos de Afiliaciones',
            },
        ),
        migrations.AddField(
            model_name='formularioafil',
            name='tipoafiliacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipoafiliacion'),
        ),
    ]
