# Generated by Django 4.2.7 on 2024-02-08 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0013_alter_actividadeconomica_uc_alter_caractbarrio_uc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiplicidad_embarazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Multiplicidad de embarazo',
                'verbose_name_plural': 'Multiplicidad de embarazos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Tipo de parto',
                'verbose_name_plural': 'Tipos de partos',
            },
        ),
        migrations.CreateModel(
            name='Sitio_parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Sitio del parto',
                'verbose_name_plural': 'Sitios donde se produjo el parto',
            },
        ),
        migrations.CreateModel(
            name='Nacido_vivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('nrocertificado', models.CharField(max_length=20, unique=True)),
                ('peso', models.IntegerField(blank=True, default=0, null=True)),
                ('talla', models.IntegerField(blank=True, default=0, null=True)),
                ('fechanac', models.DateField()),
                ('horanac', models.TimeField(blank=True, null=True)),
                ('tiempo_gestacion', models.IntegerField(blank=True, default=0, null=True)),
                ('nroconsultapren', models.IntegerField(blank=True, default=0, null=True)),
                ('apgar1', models.IntegerField(blank=True, default=0, null=True)),
                ('apgar5', models.IntegerField(blank=True, default=0, null=True)),
                ('gruposanguineo', models.CharField(blank=True, max_length=2, null=True)),
                ('factor_rh', models.CharField(blank=True, max_length=10, null=True)),
                ('pueblo_indigena', models.CharField(blank=True, max_length=150, null=True)),
                ('edad_madre', models.IntegerField(blank=True, default=0, null=True)),
                ('nrohijosnv', models.IntegerField(blank=True, default=0, null=True)),
                ('nroembarazos', models.IntegerField(blank=True, default=0, null=True)),
                ('edad_padre', models.IntegerField(blank=True, default=0, null=True)),
                ('fecharegistro', models.DateField(blank=True, null=True)),
                ('fechaultmod', models.DateField(blank=True, null=True)),
                ('Sitio_parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruaf.sitio_parto')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_nace', to='cnf.area')),
                ('certificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpto_nto', to='cnf.departamento')),
                ('etnia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.etnia')),
                ('ips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.ips')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rltd_madre', to='cnf.paciente')),
                ('multiplicidad_embarazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruaf.multiplicidad_embarazo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpio_nto', to='cnf.municipio')),
                ('paisnac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_nac', to='cnf.pais')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.sexo')),
                ('tipo_parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruaf.tipo_parto')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Certificado de nacido vivo',
            },
        ),
        migrations.CreateModel(
            name='Atiende_parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Parto atendido por',
                'verbose_name_plural': 'Parto atendido por',
            },
        ),
    ]
