# Generated by Django 4.2.7 on 2024-02-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruaf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nacido_vivo',
            old_name='Sitio_parto',
            new_name='sitio_parto',
        ),
    ]
