# Generated by Django 4.2.7 on 2024-02-12 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0014_pais_indicativo_alter_pais_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ruaf', '0002_rename_sitio_parto_nacido_vivo_sitio_parto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nacido_vivo',
            name='certificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificador', to='cnf.paciente'),
        ),
        migrations.CreateModel(
            name='SeguimientoBajoPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('hallazgos', models.TextField()),
                ('educacion', models.CharField(blank=True, choices=[('1', 'Si'), ('2', 'No')], max_length=1, null=True)),
                ('icbf', models.CharField(blank=True, choices=[('1', 'Si'), ('2', 'No')], max_length=1, null=True)),
                ('nutricionista', models.CharField(blank=True, choices=[('1', 'Si'), ('2', 'No')], max_length=1, null=True)),
                ('nacido_vivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruaf.nacido_vivo')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Seguimiento bajo peso al nacer',
            },
        ),
    ]
