# Generated by Django 4.2.7 on 2024-02-12 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ruaf', '0003_alter_nacido_vivo_certificador_seguimientobajopeso'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNacidoVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ruaf/nv/')),
                ('nacido_vivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruaf.nacido_vivo')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name_plural': 'Archivos nacidos vivos',
            },
        ),
    ]
