# Generated by Django 4.2.7 on 2024-02-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0014_pais_indicativo_alter_pais_codigo'),
        ('ruaf', '0004_filenacidovivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacido_vivo',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.eps'),
        ),
    ]
