# Generated by Django 4.2.7 on 2024-02-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruaf', '0005_nacido_vivo_eps'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientobajopeso',
            name='perimetro_cefalico',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='seguimientobajopeso',
            name='perimetro_toraxico',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='seguimientobajopeso',
            name='peso',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='seguimientobajopeso',
            name='talla',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
