# Generated by Django 4.2.7 on 2024-02-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0015_pueblo_indigena_escolaridad'),
        ('ruaf', '0007_certificador_muerte_clase_muerte_sitio_defuncion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortalidad_ruaf',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpto_def', to='cnf.departamento'),
        ),
        migrations.AlterField(
            model_name='mortalidad_ruaf',
            name='departamento_reside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpto_reside_def', to='cnf.departamento'),
        ),
        migrations.AlterField(
            model_name='mortalidad_ruaf',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpio_def', to='cnf.municipio'),
        ),
        migrations.AlterField(
            model_name='mortalidad_ruaf',
            name='municipio_reside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpio_reside_def', to='cnf.municipio'),
        ),
        migrations.AlterField(
            model_name='mortalidad_ruaf',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_nac_def', to='cnf.pais'),
        ),
        migrations.AlterField(
            model_name='mortalidad_ruaf',
            name='pais_reside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_reside_def', to='cnf.pais'),
        ),
    ]
