# Generated by Django 4.2.7 on 2024-03-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res4505', '0002_vitamina_a_prinfancia_tratamiento_ablativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fortificacion_cacera_prinfancia',
            options={'verbose_name': 'Suministro de Fortificación casera en la primera infancia', 'verbose_name_plural': 'Suministros de Fortificación casera en la primera infancia'},
        ),
        migrations.DeleteModel(
            name='Preservativos',
        ),
    ]
