# Generated by Django 4.2.7 on 2024-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res4505', '0003_alter_fortificacion_cacera_prinfancia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calidad_muestra_citologia',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
