# Generated by Django 4.2.7 on 2024-02-17 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0016_organismo_de_socorro'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='acciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguridad.acciones'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Organismos_atiende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('organismo_de_socorro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.organismo_de_socorro')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Organismos de socorro intevinientes',
            },
        ),
    ]
