# Generated by Django 4.2.7 on 2024-02-18 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_casos_acciones_organismos_atiende'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afectados',
            old_name='Paciente',
            new_name='paciente',
        ),
        migrations.AddField(
            model_name='organismos_atiende',
            name='casos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguridad.casos'),
            preserve_default=False,
        ),
    ]
