# Generated by Django 4.2.7 on 2024-02-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0016_organismo_de_socorro'),
        ('seguridad', '0003_rename_paciente_afectados_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.departamento'),
        ),
        migrations.AlterField(
            model_name='casos',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.municipio'),
        ),
    ]
