# Generated by Django 4.2.7 on 2024-04-05 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sam', '0015_actaembarcacioninter_agencianaviera_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencianaviera',
            options={'verbose_name_plural': 'Agencias navieras'},
        ),
        migrations.CreateModel(
            name='Visitaen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name_plural': 'Visita en ',
            },
        ),
        migrations.AddField(
            model_name='actaembarcacioninter',
            name='visitaen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sam.visitaen'),
            preserve_default=False,
        ),
    ]
