# Generated by Django 4.2.7 on 2024-04-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0016_alter_agencianaviera_options_visitaen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaembarcacioninter',
            name='renuevacertificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
