# Generated by Django 4.2.7 on 2024-04-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0017_actaembarcacioninter_renuevacertificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actaembarcacioninter',
            name='hora',
        ),
    ]
