# Generated by Django 4.2.7 on 2024-04-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0018_remove_actaembarcacioninter_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaembarcacioninter',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
