# Generated by Django 4.2.7 on 2024-04-06 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sam', '0019_alter_actaembarcacioninter_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEmbarcacionInterPuerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('actaembarcacioninter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.actaembarcacioninter')),
                ('puertos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.puertos')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Puertos visitados',
            },
        ),
    ]
