# Generated by Django 4.2.7 on 2024-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0021_actabodegaspatios_medidasanitaria_productoquimico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoquimicoactabodegaspatios',
            name='almacena',
            field=models.BooleanField(default=True),
        ),
    ]
