# Generated by Django 4.2.7 on 2024-04-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0023_actaviviendatransitoria_itemactaviviendatransitoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloque',
            options={'ordering': ['tipoacta', 'orden'], 'verbose_name_plural': 'Bloques de preguntas'},
        ),
        migrations.AlterModelOptions(
            name='tipoacta',
            options={'ordering': ['descripcion'], 'verbose_name_plural': 'Tipos de Actas'},
        ),
        migrations.AlterField(
            model_name='bloque',
            name='orden',
            field=models.FloatField(default=0),
        ),
    ]
