# Generated by Django 4.2.7 on 2024-04-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0025_alter_bloque_idbloque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionpregunta',
            options={'verbose_name_plural': 'Evaluaciones de preguntas'},
        ),
        migrations.AddField(
            model_name='bloque',
            name='porcentaje',
            field=models.FloatField(default=0),
        ),
    ]
