# Generated by Django 4.2.7 on 2024-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0026_alter_evaluacionpregunta_options_bloque_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='bloqueprincipal',
            field=models.BooleanField(default=False),
        ),
    ]
