# Generated by Django 4.2.7 on 2024-04-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0018_gestoresiduohospitalario'),
        ('sam', '0029_actacentrocarcelario_itemactacentrocarcelario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='actividadeconomica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.actividadeconomica'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='aislamiento',
            field=models.BooleanField(default=False, verbose_name='Aislamiento o internación de personas para evitar la transmisión de enfermedades'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='capacidad',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='capturanimales',
            field=models.BooleanField(default=False, verbose_name='Captura y observación de animales sospechosos de enfermedades transmisibles'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='carcel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='carcelmilitares',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='centromenores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='centroreclusiondamas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='centrosalaretencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='clausuratemparcial',
            field=models.BooleanField(default=False, verbose_name='Clausura temporal parcial'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='clausuratemptotal',
            field=models.BooleanField(default=False, verbose_name='Clausura temporal total'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='codigociuu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='congelacion',
            field=models.BooleanField(default=False, verbose_name='Congelación'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='controlinsectos',
            field=models.BooleanField(default=False, verbose_name='Control de insectos u otra fauna nociva o transmisora de enfermedades'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='decomiso',
            field=models.BooleanField(default=False, verbose_name='Decomiso'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='desocupacion',
            field=models.BooleanField(default=False, verbose_name='Desocupación o desalojamiento de establecimientos o vivienda'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='destruccion',
            field=models.BooleanField(default=False, verbose_name='Destrucción o desnaturalización'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='diashabileplazo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='entidadterritorialsalud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='fechafinplazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='fechainiplazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nroactamedidasanitaria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nroactatomamuestra',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nroareaprepalimentos',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nroareatalleres',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nroceldas',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nromuestrastomadas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nropatios',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nroretenidos',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nroretenidoshombres',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='nroretenidosmujeres',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='otrotiporeclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='pobregultimavisita',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='susparcialtrabajo',
            field=models.BooleanField(default=False, verbose_name='Suspensión parcial de trabajos o servicios'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='susptotaltrabservicio',
            field=models.BooleanField(default=False, verbose_name='Suspensión total de trabajos o servicios'),
        ),
        migrations.AddField(
            model_name='actacentrocarcelario',
            name='vacunacion',
            field=models.BooleanField(default=False, verbose_name='Vacunación personas o animales'),
        ),
    ]
