# Generated by Django 4.2.7 on 2024-04-12 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0030_actacentrocarcelario_actividadeconomica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actacentrocarcelario',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Acta visita a centros carcelarios'},
        ),
        migrations.RenameField(
            model_name='concepto',
            old_name='idconcepto',
            new_name='codigo',
        ),
        migrations.AddField(
            model_name='concepto',
            name='tipoacta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sam.tipoacta'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='concepto',
            unique_together={('codigo', 'tipoacta')},
        ),
        migrations.DeleteModel(
            name='CumplimientoCondSanitaria',
        ),
    ]
