# Generated by Django 4.2.7 on 2024-04-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0031_alter_actacentrocarcelario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
    ]
