# Generated by Django 4.2.7 on 2024-04-12 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0032_alter_concepto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actacentrocarcelario',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carcel_concepto', to='sam.concepto'),
        ),
    ]
