# Generated by Django 4.2.7 on 2024-04-12 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0033_alter_actacentrocarcelario_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actabodegaspatios',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sam.concepto'),
        ),
        migrations.AlterField(
            model_name='actaviviendatransitoria',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivtran_concepto', to='sam.concepto'),
        ),
    ]
