# Generated by Django 4.2.7 on 2024-04-13 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0018_gestoresiduohospitalario'),
        ('sam', '0034_alter_actabodegaspatios_concepto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaDrogueria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField()),
                ('nroacta', models.CharField(max_length=15)),
                ('identificaciondirtec', models.CharField(blank=True, max_length=20, null=True)),
                ('nombredirtec', models.CharField(blank=True, max_length=150, null=True)),
                ('resolucionapertura', models.BooleanField(default=True)),
                ('funcionantes1992', models.BooleanField(default=False)),
                ('resoluciontraslado', models.BooleanField(default=False)),
                ('tipoautorizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('inspeccionanterior', models.BooleanField(default=False)),
                ('fechaultinspeccion', models.DateTimeField(blank=True, null=True)),
                ('porcumplimientoanterior', models.FloatField(blank=True, default=0, null=True)),
                ('nroactanterior', models.CharField(blank=True, max_length=15, null=True)),
                ('puntaje', models.FloatField(default=0)),
                ('nroadministativos', models.IntegerField(blank=True, default=1, null=True)),
                ('nrooperativos', models.IntegerField(blank=True, default=1, null=True)),
                ('requerimiento', models.TextField(blank=True, null=True)),
                ('observacionautsan', models.TextField(blank=True, null=True)),
                ('observacionestable', models.TextField(blank=True, null=True)),
                ('diashabileplazo', models.IntegerField(blank=True, default=0, null=True)),
                ('fechainiplazo', models.DateField(blank=True, null=True)),
                ('fechafinplazo', models.DateField(blank=True, null=True)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drogueria_concepto', to='sam.concepto')),
                ('conceptoanterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drogueria_concepto_anterior', to='sam.concepto')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.establecimiento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.municipio')),
            ],
            options={
                'verbose_name_plural': 'Acta visita a droguerías y farmacias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name_plural': 'Perfil director técnico',
            },
        ),
        migrations.CreateModel(
            name='ItemActaDroguerias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('puntaje', models.FloatField(default=0)),
                ('habilitada', models.BooleanField(default=True)),
                ('actadrogueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.actadrogueria')),
                ('evaluacion', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sam.evaluacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.pregunta')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuncionariosActaDrogueria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('actadrogueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.actadrogueria')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.funcionario')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtiendeActaDrogueria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('identificacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=80, null=True)),
                ('actadrogueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.actadrogueria')),
                ('tipodoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.tipodoc')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='actadrogueria',
            name='perfildirector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sam.perfildirector'),
        ),
        migrations.AddField(
            model_name='actadrogueria',
            name='tipoacta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.tipoacta'),
        ),
        migrations.AddField(
            model_name='actadrogueria',
            name='tipodocdirtec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.tipodoc'),
        ),
        migrations.AddField(
            model_name='actadrogueria',
            name='uc',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatico'),
        ),
        migrations.AddField(
            model_name='actadrogueria',
            name='um',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica'),
        ),
    ]
