# Generated by Django 4.2.7 on 2024-03-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0002_alter_conglomerado_uc_alter_conglomeradomalaria_uc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malaria',
            old_name='clasiFinicial',
            new_name='clasifinicial',
        ),
    ]
