# Generated by Django 4.2.7 on 2024-03-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0003_rename_clasifinicial_malaria_clasifinicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malaria',
            options={'ordering': ['fec_not'], 'verbose_name_plural': 'Notificación Casos de Malaria - 465'},
        ),
    ]
